import { CartProvider } from "../app/context/CartContext"; // Import du contexte
import { AddressProvider } from "../app/context/AddressContext";
import { AuthProvider } from "../app/context/AuthContext";
import { ConfigProvider } from "../app/context/ConfigContext";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased font-sans">
        <ConfigProvider>
          <AuthProvider>
            <CartProvider>
              <AddressProvider> {/* Utilisation du contexte pour englober l'application */}
                {children}
              </AddressProvider>
            </CartProvider>
          </AuthProvider>
        </ConfigProvider>
      </body>
    </html>
  );
}
